package utils;

public enum EnumsForSprites {
    IS_TRAVERSABLE,
    NOT_TRAVERSABLE,
    PLAYER,
    ALLIGATOR,
    ALLIGATOR_DEN_UP,
    ALLIGATOR_DEN_DOWN,
    ALLIGATOR_DEN_RIGHT,
    ALLIGATOR_DEN_LEFT,
    GOAL,
    CHASER,
    ROCK,
    PORTAL,
    PUSHABLE_ELEMENT}

